backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images"
public_folder: "/images"
collections:
- label: "Pages"
  name: "pages"
  files:
    - label: "Home Page"
      name: "home"
      file: "content/_index.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Seo Title, name: seo_title, widget: string, required: false}
        - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
        - {label: Seo Description, name: seo_description, widget: text, required: false}
        - {label: Link, name: link, widget: string}
        - label: Slides
          name: slides
          widget: list
          fields:
            - {label: Image, name: image, widget: image}
        - {label: Content, name: body, widget: markdown}
    - label: "About"
      name: "about"
      file: "content/about/_index.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Seo Title, name: seo_title, widget: string, required: false}
        - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
        - {label: Seo Description, name: seo_description, widget: text, required: false}
        - {label: Featured Image, name: featured_image, widget: image}
        - {label: Content, name: body, widget: markdown}
    - label: "Contact Page"
      name: "contact"
      file: "content/contact/_index.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Seo Title, name: seo_title, widget: string, required: false}
        - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
        - {label: Seo Description, name: seo_description, widget: text, required: false}
        - {label: Google Map Coordinates, name: google_map_coordinates, widget: string}
        - {label: Featured Image, name: featured_image, widget: image}
        - {label: Business Name, name: business_name, widget: string}
        - {label: Business Location One, name: business_location_one, widget: string}
        - {label: Business Location Two, name: business_location_two, widget: string}
        - {label: Address One, name: address_one, widget: text}
        - {label: Phone No One, name: phone_one, widget: string}
        - {label: Fax One, name: Fax_one, widget: string}
        - {label: Email One, name: email_one, widget: string}
        - {label: Address Two, name: address_two, widget: text}
        - {label: Phone No Two, name: phone_two, widget: string}
        - {label: Fax Two, name: Fax_two, widget: string}
        - {label: Email Two, name: email_two, widget: string}
        - {label: Content, name: body, widget: markdown}
            
