backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images"
public_folder: "/images"
collections:
- label: "Pages"
  name: "pages"
  files:
    - label: "Home Page"
      name: "home"
      file: "content/_index.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Seo Title, name: seo_title, widget: string, required: false}
        - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
        - {label: Seo Description, name: seo_description, widget: text, required: false}
        - {label: Link, name: link, widget: string}
        - label: Slides
          name: slides
          widget: list
          fields:
            - {label: Image, name: image, widget: image}
        - {label: Content, name: body, widget: markdown}
- label: "Data"
  name: "data"
  files:
    - label: "Brands"
      name: "brands"
      file: "data/brands.yml"
      fields:
        - label: Brands
          name: brands
          widget: list
          fields:
            - {label: Name, name: name, widget: string}
            - {label: Image, name: image, widget: image}
    - label: "Awards"
      name: "awards"
      file: "data/awards.yml"
      fields:
        - label: Awards
          name: awards
          widget: list
          fields:
            - {label: Image, name: image, widget: image}
    - label: "Meta"
      name: "meta"
      file: "data/meta.yml"
      fields:
        - {label: Page Background, name: background_image, widget: image}
        - {label: Logo, name: logo, widget: image}
        - {label: FB Cover, name: fb_cover, widget: image}
            
